-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF SECURITY DEFINER
AS $BODY$
  begin
    insert into public.users (user_id, user_type)
    values (new.id, 'AUTH');

    insert into public.auth_users (user_id)
    values (new.id);
    return new;
  end;
$BODY$;

ALTER FUNCTION public.handle_new_auth_user()
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.handle_new_auth_user() TO authenticated;

GRANT EXECUTE ON FUNCTION public.handle_new_auth_user() TO postgres;

GRANT EXECUTE ON FUNCTION public.handle_new_auth_user() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.handle_new_auth_user() TO anon;

GRANT EXECUTE ON FUNCTION public.handle_new_auth_user() TO service_role;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    RENAME room_id TO user_id;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    RENAME room_id TO photo_url;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    RENAME room_id TO created_at;

ALTER TABLE public.standard_game_user_progresses
    ALTER COLUMN created_at TYPE timestamp with time zone  COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN created_at SET DEFAULT (now() AT TIME ZONE 'utc'::text);

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN created_at SET STORAGE PLAIN;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    RENAME room_id TO standard_role;

ALTER TABLE public.standard_game_user_progresses
    ALTER COLUMN standard_role TYPE standard_role COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN standard_role SET DEFAULT 'CIVILIAN'::standard_role;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN standard_role SET STORAGE PLAIN;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    RENAME room_id TO vote_to;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    RENAME room_id TO round;

ALTER TABLE public.standard_game_user_progresses
    ALTER COLUMN round TYPE smallint COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN round SET DEFAULT '1'::smallint;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN round DROP NOT NULL;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ALTER COLUMN round SET STORAGE PLAIN;
ALTER TABLE IF EXISTS public.standard_game_user_progresses DROP CONSTRAINT IF EXISTS standard_game_user_progresses_pkey;

ALTER TYPE public.standard_role
    ADD VALUE 'WERE_WOLF' AFTER 'WEREWOLF';
