-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Enable access to all users"
    ON public.rooms
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

CREATE POLICY "Enable insert for authenticated users only"
    ON public.rooms
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.role() = 'authenticated'::text));

ALTER TABLE IF EXISTS public.standard_game_user_progresses DROP CONSTRAINT IF EXISTS standard_game_user_progresses_room_id_fkey;

ALTER TABLE IF EXISTS public.game_results DROP CONSTRAINT IF EXISTS room_users_room_id_fkey;
