-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: standard_role

-- DROP TYPE IF EXISTS public.standard_role;

CREATE TYPE public.standard_role AS ENUM
    ('CIVILIAN', 'WEREWOLF');

ALTER TYPE public.standard_role
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.standard_game_user_progresses
(
    room_id character varying COLLATE pg_catalog."default" NOT NULL,
    user_id character varying COLLATE pg_catalog."default" NOT NULL,
    round smallint DEFAULT '1'::smallint,
    photo_url character varying COLLATE pg_catalog."default",
    standard_role standard_role NOT NULL DEFAULT 'CIVILIAN'::standard_role,
    vote_to character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    CONSTRAINT standard_game_user_progresses_pkey PRIMARY KEY (room_id, user_id),
    CONSTRAINT standard_game_user_progresses_room_id_fkey FOREIGN KEY (room_id)
        REFERENCES public.rooms (room_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT standard_game_user_progresses_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    OWNER to postgres;

ALTER TABLE IF EXISTS public.standard_game_user_progresses
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.standard_game_user_progresses TO anon;

GRANT ALL ON TABLE public.standard_game_user_progresses TO authenticated;

GRANT ALL ON TABLE public.standard_game_user_progresses TO postgres;

GRANT ALL ON TABLE public.standard_game_user_progresses TO service_role;

