-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Enable insert for every users"
    ON public.standard_game_user_progresses
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK (true);


CREATE POLICY "Enable access to all users"
    ON public.standard_game_user_progresses
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

CREATE POLICY "Enable update for users based on email"
    ON public.standard_game_user_progresses
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Enable update for auth_user"
    ON public.rooms
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() = owner_id))
    WITH CHECK ((auth.uid() = owner_id));
