-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.users FROM authenticated;
REVOKE ALL ON TABLE public.users FROM postgres;
REVOKE ALL ON TABLE public.users FROM service_role;
GRANT ALL ON TABLE public.users TO authenticated;

GRANT ALL ON TABLE public.users TO postgres;

GRANT ALL ON TABLE public.users TO service_role;

REVOKE ALL ON TABLE public.rooms FROM authenticated;
REVOKE ALL ON TABLE public.rooms FROM postgres;
REVOKE ALL ON TABLE public.rooms FROM service_role;
GRANT ALL ON TABLE public.rooms TO authenticated;

GRANT ALL ON TABLE public.rooms TO postgres;

GRANT ALL ON TABLE public.rooms TO service_role;

REVOKE ALL ON TABLE public.game_results FROM authenticated;
REVOKE ALL ON TABLE public.game_results FROM postgres;
REVOKE ALL ON TABLE public.game_results FROM service_role;
GRANT ALL ON TABLE public.game_results TO authenticated;

GRANT ALL ON TABLE public.game_results TO postgres;

GRANT ALL ON TABLE public.game_results TO service_role;

REVOKE ALL ON TABLE public.auth_users FROM authenticated;
REVOKE ALL ON TABLE public.auth_users FROM postgres;
REVOKE ALL ON TABLE public.auth_users FROM service_role;
GRANT ALL ON TABLE public.auth_users TO authenticated;

GRANT ALL ON TABLE public.auth_users TO postgres;

GRANT ALL ON TABLE public.auth_users TO service_role;

REVOKE ALL ON TABLE public.standard_game_user_progresses FROM authenticated;
REVOKE ALL ON TABLE public.standard_game_user_progresses FROM postgres;
REVOKE ALL ON TABLE public.standard_game_user_progresses FROM service_role;
GRANT ALL ON TABLE public.standard_game_user_progresses TO authenticated;

GRANT ALL ON TABLE public.standard_game_user_progresses TO postgres;

GRANT ALL ON TABLE public.standard_game_user_progresses TO service_role;

REVOKE ALL ON TABLE public.guest_users FROM authenticated;
REVOKE ALL ON TABLE public.guest_users FROM postgres;
REVOKE ALL ON TABLE public.guest_users FROM service_role;
GRANT ALL ON TABLE public.guest_users TO authenticated;

GRANT ALL ON TABLE public.guest_users TO postgres;

GRANT ALL ON TABLE public.guest_users TO service_role;
